#include <iostream> 
using namespace std;
int main()
{ 
    try
{ 
    throw 10.1; 
    
} 
  catch (int param) { 
      cout << "int exceptionn\n"; 
      
  } catch (...) 
 
  {
      cout << "default exceptionn\n";
      } 
      cout << "After Exception\n"; 
      return 0;
    
}
